### ISSUE TITLE
Optimize lock usage

### ISSUE THREAD

**Issue by LemonHX** [starcoinorg/xtor#1]
some rw locks and mutex could be replaced by optimistic spin lock

**Comment by templexxx** [comment]
> some rw locks and mutex could be replaced by optimistic spin lock

Could this be wait-free :D @LemonHX 

spin may bring cycle wasting, even using PAUSE instruction

**Comment by LemonHX** [comment]
@templexxx 
I have written a lock [optimistic lock coupling](https://github.com/LemonHX/optimistic_lock_coupling_rs)

**Comment by LemonHX** [comment]
@templexxx I don't think it is possible

**Comment by templexxx** [comment]
Unlike the optimisitc lock coupling(OLC), READ-OPTIMIZED WRITE EXCLUSION （ROWEX）could make read to wait-free.
In OLC everything operation may restart. @LemonHX If I'm not mistaken

**Comment by LemonHX** [comment]
I will take a look on ROWEX and its implementation

**Comment by LemonHX** [comment]
used DashMap and Mutex.
